/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author singha
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.10 at 02:02:11 PM IST 
//


package jaxb.wextransaction;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="batch" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="trans" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="card"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="track" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="pump" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="cat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="service" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="product" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                                       &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                                       &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="odometer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="authref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="cardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="tid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="bid" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                 &lt;attribute name="app" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batch"
})
@XmlRootElement(name = "Transactionfile")
public class Transactionfile {

    protected List<Transactionfile.Batch> batch;
    @XmlAttribute(name = "date")
    protected String date;
    @XmlAttribute(name = "time")
    protected String time;
    @XmlAttribute(name = "sequence")
    protected String sequence;

    /**
     * Gets the value of the batch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transactionfile.Batch }
     * 
     * 
     */
    public List<Transactionfile.Batch> getBatch() {
        if (batch == null) {
            batch = new ArrayList<Transactionfile.Batch>();
        }
        return this.batch;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="trans" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="card"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="track" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="pump" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="cat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="service" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="product" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="odometer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="authref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="cardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="tid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="bid" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *       &lt;attribute name="app" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trans"
    })
    public static class Batch {

        protected List<Transactionfile.Batch.Trans> trans;
        @XmlAttribute(name = "tid")
        protected String tid;
        @XmlAttribute(name = "bid")
        protected int bid;
        @XmlAttribute(name = "app")
        protected String app;
        @XmlAttribute(name = "version")
        protected String version;

        /**
         * Gets the value of the trans property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the trans property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrans().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Transactionfile.Batch.Trans }
         * 
         * 
         */
        public List<Transactionfile.Batch.Trans> getTrans() {
            if (trans == null) {
                trans = new ArrayList<Transactionfile.Batch.Trans>();
            }
            return this.trans;
        }

        /**
         * Gets the value of the tid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTid() {
            return tid;
        }

        /**
         * Sets the value of the tid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTid(String value) {
            this.tid = value;
        }

        /**
         * Gets the value of the bid property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public int getBid() {
            return bid;
        }

        /**
         * Sets the value of the bid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setBid(int value) {
            this.bid = value;
        }

        /**
         * Gets the value of the app property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApp() {
            return app;
        }

        /**
         * Sets the value of the app property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApp(String value) {
            this.app = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="card"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="track" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="pump" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="cat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="service" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="product" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="odometer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="authref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="vehicle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="cardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "card",
            "pump",
            "product",
            "odometer",
            "amount",
            "authref",
            "driver",
            "vehicle"
        })
        public static class Trans {

            @XmlElement(required = true)
            protected Transactionfile.Batch.Trans.Card card;
            protected Transactionfile.Batch.Trans.Pump pump;
            protected List<Transactionfile.Batch.Trans.Product> product;
            protected String odometer;
            protected String amount;
            protected String authref;
            protected String driver;
            protected String vehicle;
            @XmlAttribute(name = "cardCode")
            protected String cardCode;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "nbr")
            protected String nbr;
            @XmlAttribute(name = "date")
            protected String date;
            @XmlAttribute(name = "time")
            protected String time;

            /**
             * Gets the value of the card property.
             * 
             * @return
             *     possible object is
             *     {@link Transactionfile.Batch.Trans.Card }
             *     
             */
            public Transactionfile.Batch.Trans.Card getCard() {
                return card;
            }

            /**
             * Sets the value of the card property.
             * 
             * @param value
             *     allowed object is
             *     {@link Transactionfile.Batch.Trans.Card }
             *     
             */
            public void setCard(Transactionfile.Batch.Trans.Card value) {
                this.card = value;
            }

            /**
             * Gets the value of the pump property.
             * 
             * @return
             *     possible object is
             *     {@link Transactionfile.Batch.Trans.Pump }
             *     
             */
            public Transactionfile.Batch.Trans.Pump getPump() {
                return pump;
            }

            /**
             * Sets the value of the pump property.
             * 
             * @param value
             *     allowed object is
             *     {@link Transactionfile.Batch.Trans.Pump }
             *     
             */
            public void setPump(Transactionfile.Batch.Trans.Pump value) {
                this.pump = value;
            }

            /**
             * Gets the value of the product property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the product property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProduct().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Transactionfile.Batch.Trans.Product }
             * 
             * 
             */
            public List<Transactionfile.Batch.Trans.Product> getProduct() {
                if (product == null) {
                    product = new ArrayList<Transactionfile.Batch.Trans.Product>();
                }
                return this.product;
            }

            /**
             * Gets the value of the odometer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOdometer() {
                return odometer;
            }

            /**
             * Sets the value of the odometer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOdometer(String value) {
                this.odometer = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAmount(String value) {
                this.amount = value;
            }

            /**
             * Gets the value of the authref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuthref() {
                return authref;
            }

            /**
             * Sets the value of the authref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuthref(String value) {
                this.authref = value;
            }

            /**
             * Gets the value of the driver property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDriver() {
                return driver;
            }

            /**
             * Sets the value of the driver property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDriver(String value) {
                this.driver = value;
            }

            /**
             * Gets the value of the vehicle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVehicle() {
                return vehicle;
            }

            /**
             * Sets the value of the vehicle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVehicle(String value) {
                this.vehicle = value;
            }

            /**
             * Gets the value of the cardCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardCode() {
                return cardCode;
            }

            /**
             * Sets the value of the cardCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardCode(String value) {
                this.cardCode = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the nbr property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public String getNbr() {
                return nbr;
            }

            /**
             * Sets the value of the nbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setNbr(String value) {
                this.nbr = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the time property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public String getTime() {
                return time;
            }

            /**
             * Sets the value of the time property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTime(String value) {
                this.time = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="track" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Card {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "track")
                protected String track;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the track property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public String getTrack() {
                    return track;
                }

                /**
                 * Sets the value of the track property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setTrack(String value) {
                    this.track = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
             *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
             *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "amount",
                "quantity",
                "price"
            })
            public static class Product {

                protected String amount;
                protected String quantity;
                protected String price;
                @XmlAttribute(name = "code")
                protected String code;

                /**
                 * Gets the value of the amount property.
                 * 
                 */
                public String getAmount() {
                    return amount;
                }

                /**
                 * Sets the value of the amount property.
                 * 
                 */
                public void setAmount(String value) {
                    this.amount = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 */
                public String getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 */
                public void setQuantity(String value) {
                    this.quantity = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 */
                public String getPrice() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 */
                public void setPrice(String value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="cat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="service" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "amount"
            })
            public static class Pump {

                protected String amount;
                @XmlAttribute(name = "cat")
                protected String cat;
                @XmlAttribute(name = "service")
                protected String service;
                @XmlAttribute(name = "nbr")
                protected int nbr;

                /**
                 * Gets the value of the amount property.
                 * 
                 */
                public String getAmount() {
                    return amount;
                }

                /**
                 * Sets the value of the amount property.
                 * 
                 */
                public void setAmount(String value) {
                    this.amount = value;
                }

                /**
                 * Gets the value of the cat property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCat() {
                    return cat;
                }

                /**
                 * Sets the value of the cat property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCat(String value) {
                    this.cat = value;
                }

                /**
                 * Gets the value of the service property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getService() {
                    return service;
                }

                /**
                 * Sets the value of the service property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setService(String value) {
                    this.service = value;
                }

                /**
                 * Gets the value of the nbr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public int getNbr() {
                    return nbr;
                }

                /**
                 * Sets the value of the nbr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setNbr(int value) {
                    this.nbr = value;
                }

            }

        }

    }

}
