#!/bin/bash

# Do this once when you first check out the project.

repo=file:///home/mercadoch/work/VisionPlusGateway/VisionPlusGateway-ejb/repo/

rm -rf com 

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=com.ibm.mq-5.3.07.jar \
	-DgroupId=com.ibm \
	-DartifactId=com.ibm.mq \
	-Dpackaging=jar \
	-Dversion=5.3.07

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=com.ibm.mq.jmqi-7.5.02.jar \
	-DgroupId=com.ibm.mq \
	-DartifactId=jmqi \
	-Dpackaging=jar \
	-Dversion=7.5.02

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=com.ibm.mq.headers-7.5.02.jar \
	-DgroupId=com.ibm \
	-DartifactId=com.ibm.mq.headers \
	-Dpackaging=jar \
	-Dversion=7.5.02

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=com.ibm.mqjms-7.5.02.jar \
	-DgroupId=com.ibm \
	-DartifactId=com.ibm.mqjms \
	-Dpackaging=jar \
	-Dversion=7.5.02

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=dhbcore-7.5.02.jar \
	-DgroupId=com.ibm \
	-DartifactId=dhbcore \
	-Dpackaging=jar \
	-Dversion=7.5.02

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=fscontext-7.5.02.jar \
	-DgroupId=com.ibm \
	-DartifactId=fscontext \
	-Dpackaging=jar \
	-Dversion=7.5.02

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=com.ibm.mq.jmqi-7.5.02.jar \
	-DgroupId=com.ibm \
	-DartifactId=com.ibm.mq.jmqi \
	-Dpackaging=jar \
	-Dversion=5.3.07

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=com.ibm.mq.commonservices-7.5.02.jar \
	-DgroupId=com.ibm \
	-DartifactId=com.ibm.mq.commonservices \
	-Dpackaging=jar \
	-Dversion=7.5.02

mvn deploy:deploy-file \
	-Durl=$repo \
	-Dfile=jms-1.1.jar \
	-DgroupId=javax.jms \
	-DartifactId=jms \
	-Dpackaging=jar \
	-Dversion=1.1

